### ISSUE TITLE
Puzzle solved but no rating points awarded

### ISSUE THREAD

**Issue by BeVegan-savetheworld** [benckx/elephantchess.io#25]
![Screenshot_2023-03-25-22-52-21-156_com android chrome](https://user-images.githubusercontent.com/128917729/227726716-b5b8a8cd-95c3-4705-980f-22bf29163eb9.jpg)

Puzzle is solved successfully but no rating points are awarded. It shows n/a

**Comment by benckx** [comment]
Your rating is 1409 and the puzzle is 800. The difference is just too large, so the elo was rounded to 0.

This is how it's calculated:
https://medium.com/purple-theory/what-is-elo-rating-c4eb7a9061e0

Maybe we could round to 1 to avoid confusion...

**Comment by BeVegan-savetheworld** [comment]
Rounded up would be nice 🙂

**Comment by benckx** [comment]
Ok I'll round up for now.
