### ISSUE TITLE
Make clock colors consistent with board orientation

### ISSUE THREAD

**Issue by benckx** [benckx/elephantchess.io#73]
And maybe also always have the names of player next to the counter.

For example like Lichess:
![Image](https://user-images.githubusercontent.com/8626080/263464538-02fc92ea-8f35-4124-8383-c74acaba53e6.png)

**Comment by lucaferranti** [comment]
yep this would be very nice to have, currently when playing with red I have my oppponent clock on my side, which is a bit confusing.

![image](https://github.com/user-attachments/assets/fb04a447-e4f6-4bf3-b59d-dc3902843be9)

**Comment by benckx** [comment]
@lucaferranti okay I moved this in the planning to pick it up next. I'd like to finish a bit what I was doing with the mobile version first.

**Comment by benckx** [comment]
Just finished this, I will deploy now.

![Screenshot from 2024-11-02 15-53-36](https://github.com/user-attachments/assets/7e63182a-19b1-4ccf-89d2-8b3b805b7b89)
