### ISSUE TITLE
Filter puzzle by one move puzzle kill, allow to have no difficulty progression.

### ISSUE THREAD

**Issue by somchai-x** [benckx/elephantchess.io#82]

**Comment by benckx** [comment]
what does it mean "allow to have no difficulty progression"?

**Comment by benckx** [comment]
Actually my plan is to be able to browser puzzles by category, but then the k won't be 16 by default (when you solved it).

**Comment by somchai-x** [comment]
Currently, When user do a puzzle correctly. do they get more difficult problems ?

**Comment by benckx** [comment]
Not directly, but the next problem is picked within a rating range.

**Comment by benckx** [comment]
Yes I'd like to implement something so you can play puzzles from a certain category.
